"""Service-owned auth lifecycle implementations.

Generated by code_951_990. This module owns lifecycle logic that was
temporarily preserved as private helpers in app.api_v2_routers.auth.
"""

from datetime import datetime, timedelta, timezone

from sqlalchemy.ext.asyncio import AsyncSession
from fastapi import HTTPException, Request, Response, status

from app.api_v2_deps.auth_runtime import AuthRuntimeContext
from app.core.config import settings
from app.core.refresh_tokens import store_refresh_token, consume_refresh_token
from app.core.security import (
    create_access_token,
    create_refresh_token,
    decode_token,
    encrypt_pii,
    hash_email,
    hash_password,
    verify_password,
)
from app.services.fourth_estate import FourthEstateService
from app.services.dev_diagnostic_seed import seed_dev_diagnostic_items
from app.domain.schemas import LoginRequest, RefreshRequest, RegisterRequest, TokenResponse
from app.models import UserRole

# Constants moved from auth.py
DEV_GUARDIAN_EMAIL = "dev.guardian" + "@" + "eduboost.local"
DEV_GUARDIAN_PASSWORD = "DevPass1234!"
DEV_GUARDIAN_NAME = "Dev Guardian"
DEV_LEARNER_NAME = "DevLearner"
REFRESH_COOKIE = "eduboost_refresh"
DEV_CONSENT_POLICY_VERSION = "1.0.0"


def _normalise_role_value(role):
    value = getattr(role, "value", role)
    text = str(value or "").strip()
    if "." in text:
        text = text.rsplit(".", 1)[-1]
    return text.lower()


async def _ensure_dev_session_consent(consent_repo, *, guardian_id, learner_id):
    """Create or normalise dev-session consent to the active runtime policy.

    The runtime consent gate requires semantic version 1.0.0. Historical local
    dev sessions used 1.0, which makes a newly bootstrapped learner fail the
    next learner-scoped request with consent_required. For dev-session only,
    normalise the latest not-revoked row in place to avoid partial unique-index
    collisions, or create a row if none exists.
    """
    active = await consent_repo.get_active(learner_id)
    latest = None
    if active is None and hasattr(consent_repo, "get_latest_for_learner"):
        latest = await consent_repo.get_latest_for_learner(learner_id)

    candidate = active or latest
    if candidate is not None and getattr(candidate, "revoked_at", None) is None:
        candidate.guardian_id = guardian_id
        candidate.policy_version = DEV_CONSENT_POLICY_VERSION
        if hasattr(candidate, "status"):
            candidate.status = "granted"
        if hasattr(candidate, "expires_at"):
            candidate.expires_at = datetime.now(timezone.utc) + timedelta(days=365)
        return candidate

    return await consent_repo.create(
        guardian_id=guardian_id,
        learner_id=learner_id,
        policy_version=DEV_CONSENT_POLICY_VERSION,
    )


def _canonical_access_claims(user, *, existing_claims=None, extra=None):
    """Build canonical access token claims."""
    from app.services.auth_token_claims import build_access_token_claims
    return build_access_token_claims(user, existing_claims=existing_claims, extra=extra)


def _set_refresh_cookie(response: Response, refresh: str) -> None:
    """Set refresh token in HTTP-only cookie."""
    response.set_cookie(
        key=REFRESH_COOKIE,
        value=refresh,
        max_age=60 * 60 * 24 * 30,
        secure=True,
        httponly=True,
        samesite="strict",
    )


async def _maybe_await(value):
    if hasattr(value, '__await__'):
        return await value
    return value


async def create_dev_session_impl(
    response: Response,
    db: AsyncSession,
    auth_runtime: AuthRuntimeContext):
    """
    Non-production bootstrap endpoint for the local learner flow.
    Creates or reuses a guardian, learner, and active consent so the frontend
    can exercise authenticated V2 routes without hand-editing localStorage.
    """
    if settings.is_production():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Not found")

    guardian_repo = auth_runtime.guardian_repo
    learner_repo = auth_runtime.learner_repo
    consent_repo = auth_runtime.consent_repo
    audit = FourthEstateService(db)

    email_hash = hash_email(DEV_GUARDIAN_EMAIL)
    guardian = await guardian_repo.get_by_email_hash(email_hash)
    if guardian is None:
        guardian = await guardian_repo.create(
            email_hash=email_hash,
            email_encrypted=encrypt_pii(DEV_GUARDIAN_EMAIL.lower().strip()),
            display_name=DEV_GUARDIAN_NAME,
            role=UserRole.PARENT,
            password_hash=hash_password(DEV_GUARDIAN_PASSWORD))

    existing_profiles = await learner_repo.get_by_guardian(guardian.id) if learner_repo is not None else []
    learner = next((item for item in existing_profiles if item.display_name == DEV_LEARNER_NAME), None)
    if learner is None:
        learner = await learner_repo.create(
            guardian_id=guardian.id,
            display_name=DEV_LEARNER_NAME,
            grade=3,
            language="en")

    await _ensure_dev_session_consent(
        consent_repo,
        guardian_id=guardian.id,
        learner_id=learner.id,
    )
    await seed_dev_diagnostic_items(db, grade=int(getattr(learner, "grade", 3) or 3))

    role_value = _normalise_role_value(guardian.role)
    refresh = create_refresh_token(guardian.id, role_value)
    refresh_payload = decode_token(refresh)

    # Include the learner IDs in the access token so authorization logic works
    learner_ids = [str(item.id) for item in existing_profiles]
    if str(learner.id) not in learner_ids:
        learner_ids.append(str(learner.id))

    guardian.guardian_learner_ids = learner_ids
    claims = _canonical_access_claims(
        guardian,
        extra={
            "refresh_jti": refresh_payload.get("jti"),
            "refresh_family": refresh_payload.get("family"),
            "guardian_learner_ids": learner_ids
        }
    )
    access = create_access_token(guardian.id, role_value, claims)
    await store_refresh_token(refresh)
    _set_refresh_cookie(response, refresh)
    await audit.auth_event("DEV_SESSION_BOOTSTRAPPED", guardian.id, {"learner_id": learner.id})

    return {
        "access_token": access,
        "token_type": "bearer",
        "expires_in": 900,
        "guardian_id": guardian.id,
        "learner": {
            "learner_id": learner.id,
            "id": learner.id,
            "display_name": learner.display_name,
            "nickname": learner.display_name,
            "grade": learner.grade,
            "language": getattr(learner.language, "value", learner.language),
            "avatar": 0,
            "streak_days": learner.streak_days,
        },
    }


async def login_impl(
    request: Request,
    body: LoginRequest,
    response: Response,
    db: AsyncSession,
    auth_runtime: AuthRuntimeContext):
    repo = auth_runtime.guardian_repo
    audit = FourthEstateService(db)

    submitted_email = getattr(body, "email")
    email_hash = hash_email(submitted_email)
    guardian = await repo.get_by_email_hash(email_hash)
    if not guardian or not verify_password(body.password, guardian.password_hash):
        await audit.auth_event("USER_LOGIN_FAILED", guardian.id if guardian else None, {"email_hash": email_hash})
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid credentials")

    refresh = create_refresh_token(guardian.id, guardian.role)
    refresh_payload = decode_token(refresh)
    claims = _canonical_access_claims(
        guardian,
        extra={"refresh_jti": refresh_payload.get("jti"), "refresh_family": refresh_payload.get("family")}
    )
    access = create_access_token(guardian.id, guardian.role, claims)

    await store_refresh_token(refresh)
    _set_refresh_cookie(response, refresh)
    await audit.auth_event("USER_LOGIN", guardian.id)

    return TokenResponse(access_token=access, expires_in=900)


async def refresh_impl(
    request: Request,
    response: Response,
    body: RefreshRequest | None,
    db: AsyncSession,
    cookie_refresh: str | None,
    auth_runtime: AuthRuntimeContext):
    token = (body.refresh_token if body else None) or cookie_refresh
    if not token:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Refresh token required")

    payload = await consume_refresh_token(token)

    repo = auth_runtime.guardian_repo
    guardian = await repo.get_by_id(payload["sub"])
    if not guardian or not guardian.is_active:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Account inactive")

    new_refresh = create_refresh_token(guardian.id, guardian.role, family_id=payload.get("family"))
    new_refresh_payload = decode_token(new_refresh)

    # Query guardian_learner_ids to ensure they are preserved/updated correctly!
    guardian_learner_ids = await auth_runtime.guardian_learner_ids(guardian.id)
    guardian.guardian_learner_ids = [str(item) for item in guardian_learner_ids]

    claims = _canonical_access_claims(
        guardian,
        extra={"refresh_jti": new_refresh_payload.get("jti"), "refresh_family": new_refresh_payload.get("family")}
    )
    access = create_access_token(guardian.id, guardian.role, claims)
    await store_refresh_token(new_refresh)
    await FourthEstateService(db).auth_event("USER_TOKEN_REFRESHED", guardian.id)
    _set_refresh_cookie(response, new_refresh)

    return TokenResponse(access_token=access, expires_in=900)


async def register_impl(
    request: Request,
    body: RegisterRequest,
    response: Response,
    db: AsyncSession,
    auth_runtime: AuthRuntimeContext):
    repo = auth_runtime.guardian_repo
    audit = FourthEstateService(db)

    submitted_email = getattr(body, "email")
    email_hash = hash_email(submitted_email)
    if await repo.get_by_email_hash(email_hash):
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Email already registered")

    role = UserRole(body.role)
    guardian = await repo.create(
        email_hash=email_hash,
        email_encrypted=encrypt_pii(submitted_email.lower().strip()),
        display_name=body.display_name,
        role=role,
        password_hash=hash_password(body.password))

    refresh = create_refresh_token(guardian.id, guardian.role)
    refresh_payload = decode_token(refresh)
    claims = _canonical_access_claims(
        guardian,
        extra={"refresh_jti": refresh_payload.get("jti"), "refresh_family": refresh_payload.get("family")}
    )
    access = create_access_token(guardian.id, guardian.role, claims)

    await store_refresh_token(refresh)
    _set_refresh_cookie(response, refresh)
    await audit.auth_event("USER_REGISTERED", guardian.id, {"role": role.value})

    return TokenResponse(access_token=access, expires_in=900)


__all__ = [
    'create_dev_session_impl',
    'login_impl',
    'refresh_impl',
    'register_impl',
]
