#!/usr/bin/env python3
"""
scripts/generate_consent_gate_inventory.py
§4.2 – Scans all FastAPI routers and produces a consent gate inventory.
Writes docs/security/popia_consent_gate_inventory.md.

Usage:
    python scripts/generate_consent_gate_inventory.py
"""
from __future__ import annotations

import ast
import os
import sys
from pathlib import Path

ROUTER_DIR = Path(__file__).parent.parent / "app" / "api_v2_routers"
OUT_FILE = Path(__file__).parent.parent / "docs" / "security" / "popia_consent_gate_inventory.md"

CONSENT_GATE_MARKERS = {"require_active_consent", "ActiveConsent"}


def _find_routes(path: Path) -> list[dict]:
    """Walk a router file and find all HTTP route functions."""
    source = path.read_text()
    tree = ast.parse(source)
    routes = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        for decorator in node.decorator_list:
            if not isinstance(decorator, ast.Call):
                continue
            attr = decorator.func
            if not (isinstance(attr, ast.Attribute) and attr.attr in
                    {"get", "post", "put", "patch", "delete"}):
                continue
            method = attr.attr.upper()
            # Extract path
            route_path = ""
            if decorator.args:
                arg = decorator.args[0]
                if isinstance(arg, ast.Constant):
                    route_path = arg.value

            # Check for consent gate in function signature
            func_source = ast.unparse(node)
            has_gate = any(m in func_source for m in CONSENT_GATE_MARKERS)

            routes.append({
                "file": path.name,
                "function": node.name,
                "method": method,
                "path": route_path,
                "has_consent_gate": has_gate,
            })
    return routes


def main() -> int:
    all_routes: list[dict] = []
    for py_file in sorted(ROUTER_DIR.glob("*.py")):
        if py_file.name.startswith("_"):
            continue
        all_routes.extend(_find_routes(py_file))

    missing = [r for r in all_routes if not r["has_consent_gate"]
               and r["path"] and "popia" not in r["path"]]

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with OUT_FILE.open("w") as f:
        f.write("# POPIA Consent Gate Inventory\n\n")
        f.write("Auto-generated by `scripts/generate_consent_gate_inventory.py`.\n\n")
        f.write("| Method | Path | File | Function | Consent Gate |\n")
        f.write("|--------|------|------|----------|--------------|\n")
        for r in all_routes:
            gate = "✅" if r["has_consent_gate"] else "❌"
            f.write(
                f"| {r['method']} | `{r['path']}` | {r['file']} "
                f"| `{r['function']}` | {gate} |\n"
            )
        f.write("\n")
        if missing:
            f.write(f"## ❌ {len(missing)} route(s) missing consent gate\n\n")
            for r in missing:
                f.write(f"- `{r['method']} {r['path']}` in `{r['file']}`\n")

    print(f"Wrote {OUT_FILE}")
    if missing:
        print(f"WARNING: {len(missing)} routes are missing consent gates.", file=sys.stderr)
        return 1
    print(f"All {len(all_routes)} routes have consent gates.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
